server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunpxit163/cloude_server.git
          username: sunpxit@126.com
          password: sWA09035213 #GitHub上面的git仓库名字



